name: Scope Testing

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Check if SCOPE_DSN is set
      run: if [ "${{secrets.SCOPE_DSN}}" = "" ]; then exit 1; fi
    - uses: actions/checkout@v1
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Build dependencies
      run: carthage bootstrap --platform iOS
    - name: Scope for iOS
      uses: undefinedlabs/scope-for-ios-action@v1
      with:
        dsn: ${{ secrets.SCOPE_DSN }}
        project: DuckDuckGo.xcodeproj
        scheme: DuckDuckGo
